title: Chinou Thao Home Page
description: > # this means to ignore newlines until "baseurl:"
  Home page for Chinou Thao.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chinouthao.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Chinou Thao # add your name
author-img:  apple-touch-icon.jpg # add your photo
about-author: Student at St. John's University (Senior). # add description
social-google: citations?user=3o3TleEAAAAJ&hl=en
social-stack-overflow: users/4480512/michael-heroux
social-github: chinouthao # add your Github handle
social-linkedin: chinou-thao-93a45418a # add your Linkedin handle
social-email: chinouthao11@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
